// uic schema pass — a schema module (structs + enums, no widgets) becomes
// a self-contained C++ header: the snapshot a generated UI renders.
//
// The emitted types are deliberately austere: fixed-size, trivially
// copyable, no pointers, no strings, no ownership — texture references
// are ui::TextureId, text-ish data is fixed char arrays. The header
// static_asserts that contract per struct, so "the snapshot is POD for
// the renderer" is machine-enforced, not a convention.
#include "uic/uic.hpp"

#include <cctype>
#include <cstdint>
#include <map>
#include <set>
#include <sstream>

namespace uic {

namespace {

struct TypeInfo {
  std::string cpp;
  bool isEnum = false;
};

// FNV-1a, matching the emitted sid() exactly — used to detect a collision
// within one inline-enum value set at codegen (a free static check)
uint32_t sidHash(const std::string &s) {
  uint32_t h = 2166136261u;
  for (const unsigned char c : s) {
    h ^= c;
    h *= 16777619u;
  }
  return h;
}

// builtin scalar map — the schema's vocabulary
const char *builtinType(const std::string &t) {
  if (t == "int") {
    return "int32_t";
  }
  if (t == "float") {
    return "float";
  }
  if (t == "bool") {
    return "bool";
  }
  if (t == "texture") {
    return "ui::TextureId";
  }
  if (t == "char") {
    return "char";
  }
  return nullptr;
}

} // namespace

std::string emitSchemaHeader(const Module &m, std::string_view ns,
                             std::vector<Diag> &diags) {
  std::ostringstream os;
  std::set<std::string> enums;
  std::set<std::string> structs;
  for (const EnumDecl &e : m.enums) {
    enums.insert(e.name);
  }

  auto resolve = [&](const StructField &f) -> TypeInfo {
    if (f.isEnum()) {
      // an inline-enum field: a uint32_t sid. Hash the values now and
      // hard-error on any clash (the free static check).
      std::set<uint32_t> seen;
      for (const std::string &v : f.enumValues) {
        if (!seen.insert(sidHash(v)).second) {
          diags.push_back({m.name, f.line, 0,
                           "field '" + f.name + "': two values collide under "
                           "sid() — rename one"});
        }
      }
      return {"uint32_t", false};
    }
    if (const char *b = builtinType(f.type)) {
      return {b, false};
    }
    if (enums.count(f.type) != 0) {
      return {f.type, true};
    }
    if (structs.count(f.type) != 0) {
      return {f.type, false};
    }
    diags.push_back({m.name, f.line, 0,
                     "unknown type '" + f.type + "' for field '" + f.name +
                         "' (declare structs/enums before use)"});
    return {"int32_t", false};
  };

  os << "#pragma once\n"
     << "// GENERATED by uic --schema from " << m.name
     << ".ui -- DO NOT EDIT.\n"
     << "// The snapshot a generated UI renders: fixed-size, trivially\n"
     << "// copyable, no pointers/strings/paths (texture references are\n"
     << "// ui::TextureId; the asserts below enforce the contract).\n"
     << "#include \"paint/sink.hpp\"\n\n"
     << "#include <array>\n"
     << "#include <cstdint>\n"
     << "#include <type_traits>\n\n"
     << "namespace " << ns << " {\n\n"
     // an inline-enum field is a uint32_t sid — the FNV-1a of its value,
     // folded at compile time. Same string -> same id everywhere (schema,
     // panel, host), so `==` is a plain uint32_t compare across headers,
     // no shared enum type. One constexpr home, no guard needed.
     << "constexpr uint32_t sid(const char *s) {\n"
     << "  uint32_t h = 2166136261u;\n"
     << "  while (*s != 0) { h ^= (uint32_t)(unsigned char)*s++; h *= "
        "16777619u; }\n"
     << "  return h;\n"
     << "}\n\n";

  // Inline-enum id constants are NOT defined here: a codegen pass can invent
  // a param-only enum whose values no schema field mentions, so this header
  // cannot be their single home. Each generated panel emits the ids IT uses
  // (inline, folded to the sid literal — identical defs across translation
  // units agree). We only VALIDATE that a struct's own enum values don't
  // collide under sid().
  {
    std::map<std::string, std::string> byName; // UPPER -> value
    for (const StructDecl &s : m.structs) {
      for (const StructField &f : s.fields) {
        for (const std::string &v : f.enumValues) {
          std::string up = v;
          for (char &c : up) {
            c = static_cast<char>(std::toupper((unsigned char)c));
          }
          const auto ins = byName.emplace(up, v);
          if (!ins.second && ins.first->second != v) {
            diags.push_back({m.name, f.line, 0,
                             "enum values '" + ins.first->second + "' and '" +
                             v + "' share the constant '" + up + "'"});
          }
        }
      }
    }
  }

  for (const EnumDecl &e : m.enums) {
    os << "enum class " << e.name << " : int32_t {\n";
    for (const EnumEntry &entry : e.entries) {
      os << "  " << entry.name;
      if (entry.hasValue) {
        os << " = " << entry.value;
      }
      os << ",\n";
    }
    os << "};\n\n";
  }

  for (const StructDecl &s : m.structs) {
    os << "struct " << s.name << " {\n";
    for (const StructField &f : s.fields) {
      const TypeInfo t = resolve(f);
      os << "  ";
      if (f.arrayLen > 0) {
        os << "std::array<" << t.cpp << ", " << f.arrayLen << "> " << f.name
           << "{};";
      } else {
        os << t.cpp << ' ' << f.name;
        if (f.hasDefault) {
          if (f.isEnum()) {
            // the id folded at emit time — no named constant lives here
            char idbuf[16];
            std::snprintf(idbuf, sizeof idbuf, "0x%08Xu",
                          sidHash(f.defaultValue));
            os << " = " << idbuf << " /* " << f.defaultValue << " */";
          } else if (t.isEnum) {
            os << " = " << f.type << "::" << f.defaultValue;
          } else {
            os << " = " << f.defaultValue;
          }
        } else {
          os << "{}";
        }
        os << ';';
      }
      os << '\n';
    }
    os << "};\n"
       << "static_assert(std::is_trivially_copyable_v<" << s.name
       << "> && std::is_standard_layout_v<" << s.name << ">);\n\n";
    structs.insert(s.name);
  }

  os << "} // namespace " << ns << "\n";
  return os.str();
}

} // namespace uic
