// uic schema pass — a schema module (structs + enums, no widgets) becomes
// a self-contained C++ header: the snapshot a generated UI renders.
//
// The emitted types are deliberately austere: fixed-size, trivially
// copyable, no pointers, no strings, no ownership — texture references
// are ui::TextureId, text-ish data is fixed char arrays. The header
// static_asserts that contract per struct, so "the snapshot is POD for
// the renderer" is machine-enforced, not a convention.
#include "uic/uic.hpp"

#include <set>
#include <sstream>

namespace uic {

namespace {

struct TypeInfo {
  std::string cpp;
  bool isEnum = false;
};

// builtin scalar map — the schema's vocabulary
const char *builtinType(const std::string &t) {
  if (t == "int") {
    return "int32_t";
  }
  if (t == "float") {
    return "float";
  }
  if (t == "bool") {
    return "bool";
  }
  if (t == "texture") {
    return "ui::TextureId";
  }
  if (t == "char") {
    return "char";
  }
  return nullptr;
}

} // namespace

std::string emitSchemaHeader(const Module &m, std::string_view ns,
                             std::vector<Diag> &diags) {
  std::ostringstream os;
  std::set<std::string> enums;
  std::set<std::string> structs;
  for (const EnumDecl &e : m.enums) {
    enums.insert(e.name);
  }

  auto resolve = [&](const StructField &f) -> TypeInfo {
    if (const char *b = builtinType(f.type)) {
      return {b, false};
    }
    if (enums.count(f.type) != 0) {
      return {f.type, true};
    }
    if (structs.count(f.type) != 0) {
      return {f.type, false};
    }
    diags.push_back({m.name, f.line, 0,
                     "unknown type '" + f.type + "' for field '" + f.name +
                         "' (declare structs/enums before use)"});
    return {"int32_t", false};
  };

  os << "#pragma once\n"
     << "// GENERATED by uic --schema from " << m.name
     << ".ui -- DO NOT EDIT.\n"
     << "// The snapshot a generated UI renders: fixed-size, trivially\n"
     << "// copyable, no pointers/strings/paths (texture references are\n"
     << "// ui::TextureId; the asserts below enforce the contract).\n"
     << "#include \"paint/sink.hpp\"\n\n"
     << "#include <array>\n"
     << "#include <cstdint>\n"
     << "#include <type_traits>\n\n"
     << "namespace " << ns << " {\n\n";

  for (const EnumDecl &e : m.enums) {
    os << "enum class " << e.name << " : int32_t {\n";
    for (const EnumEntry &entry : e.entries) {
      os << "  " << entry.name;
      if (entry.hasValue) {
        os << " = " << entry.value;
      }
      os << ",\n";
    }
    os << "};\n\n";
  }

  for (const StructDecl &s : m.structs) {
    os << "struct " << s.name << " {\n";
    for (const StructField &f : s.fields) {
      const TypeInfo t = resolve(f);
      os << "  ";
      if (f.arrayLen > 0) {
        os << "std::array<" << t.cpp << ", " << f.arrayLen << "> " << f.name
           << "{};";
      } else {
        os << t.cpp << ' ' << f.name;
        if (f.hasDefault) {
          if (t.isEnum) {
            os << " = " << f.type << "::" << f.defaultValue;
          } else {
            os << " = " << f.defaultValue;
          }
        } else {
          os << "{}";
        }
        os << ';';
      }
      os << '\n';
    }
    os << "};\n"
       << "static_assert(std::is_trivially_copyable_v<" << s.name
       << "> && std::is_standard_layout_v<" << s.name << ">);\n\n";
    structs.insert(s.name);
  }

  os << "} // namespace " << ns << "\n";
  return os.str();
}

} // namespace uic
